BlaaBog/SBO.BlaaBog.Web/Pages/Account.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.OpenApi.Extensions;
using SBO.BlaaBog.Domain.Entities;
using SBO.BlaaBog.Services.Services;
using SBO.BlaaBog.Web.DTO;
using SBO.BlaaBog.Web.Extensions.DataAnnotations;
using SBO.BlaaBog.Web.Utils;
using System.ComponentModel.DataAnnotations;
using BC = BCrypt.Net.BCrypt;

namespace SBO.BlaaBog.Web.Pages
{
    public class AccountModel : PageModel
    {
        private readonly StudentService _service;
        private readonly IWebHostEnvironment _environment;
        public AccountModel(IWebHostEnvironment environment)
        {
            _service = new StudentService();
            _environment = environment;
        }

        [BindProperty]
        public StudentAccountDTO Student { get; set; }
        public List<SelectListItem> SpecialitiesList { get; set; } = new List<SelectListItem>();
        public string ImageName { get; set; }
        public async Task<IActionResult> OnGetAsync()
        {
            try
            {
                if (HttpContext.Items["User"] is Teacher)
                {
                    return RedirectToPage("/Teachers/Register");
                }

                Student? student = await _service.GetStudentAsync(Convert.ToInt32(HttpContext.Session.GetInt32("Id")));

                Student = new StudentAccountDTO
                {
                    Name = student.Name,
                    Description = student.Description,
                    Email = student.Email,
                    Speciality = student.Speciality,
                    EndDate = student.EndDate
                };

                foreach (Specialities speciality in Enum.GetValues<Specialities>())
                {
                    SpecialitiesList.Add(new SelectListItem { Text = EnumExtensions.GetDisplayName(speciality), Value = speciality.ToString(), Selected = speciality == student.Speciality });
                }

                ImageName = student.Image;
            }
            catch (Exception ex)
            {
                await Console.Out.WriteLineAsync(ex.Message);
                HttpContext.Session.AddToastNotification(new ToastNotification { Message = "Something went wrong!", Status = ToastColor.Danger });

            }

            return Page();
        }

        #region Change Account Details

        public async Task<IActionResult> OnPostChangeAccountDetailsAsync()
        {
            try
            {
                ModelState.Remove(nameof(Image));
                ModelState.Remove(nameof(Password));

                bool emailExists = await _service.GetStudentByEmailAsync(Student.Email) != null;
                Student oldStudent = await _service.GetStudentAsync(Convert.ToInt32(HttpContext.Session.GetInt32("Id")));

                if (emailExists && oldStudent.Email != Student.Email)
                {
                    ModelState.AddModelError("Student.Email", "Email already exists.");
                }

                if (ModelState.GetFieldValidationState("Student.Name") == ModelValidationState.Valid
                    && ModelState.GetFieldValidationState("Student.Email") == ModelValidationState.Valid
                    && ModelState.GetFieldValidationState("Student.Speciality") == ModelValidationState.Valid
                    && ModelState.GetFieldValidationState("Student.EndDate") == ModelValidationState.Valid
                    && ModelState.GetFieldValidationState("Student.Description") == ModelValidationState.Valid)
                {
                    Student updatedStudent = new Student(Convert.ToInt32(HttpContext.Session.GetInt32("Id")), Student.Name, oldStudent.Image, Student.Description ?? "", Student.Email, Student.Speciality, oldStudent.ClassId, Student.EndDate, oldStudent.Password);
                    await _service.UpdateStudentAsync(updatedStudent);
                    HttpContext.Session.SetString("Name", Student.Name);
                    HttpContext.Session.AddToastNotification(new ToastNotification { Message = "Account details have been changed!", Status = ToastColor.Success });
                    return Redirect("/Account");
                }
            }
            catch (Exception ex)
            {
                await Console.Out.WriteLineAsync(ex.Message);
                ModelState.AddModelError("Student", "Something went wrong");
            }

            return await OnGetAsync();
        }
        #endregion

        #region Change Password

        [BindProperty]
        public ChangePasswordDTO Password { get; set; }

        public async Task<IActionResult> OnPostChangePasswordAsync()
        {
            try
            {
                ModelState.Remove(nameof(Image));

                Student student = await _service.GetStudentAsync(Convert.ToInt32(HttpContext.Session.GetInt32("Id")));
                bool validatePassword = BC.EnhancedVerify(Password.Old ?? String.Empty, student.Password);

                if (validatePassword)
                {
                    if (ModelState.GetFieldValidationState("Password.Old") == ModelValidationState.Valid
                    && ModelState.GetFieldValidationState("Password.New") == ModelValidationState.Valid
                    && ModelState.GetFieldValidationState("Password.Confirm") == ModelValidationState.Valid)
                    {
                        Student updatedStudent = new Student(Convert.ToInt32(HttpContext.Session.GetInt32("Id")), student.Name, student.Image, student.Description, student.Email, student.Speciality, student.ClassId, student.EndDate, BC.EnhancedHashPassword(Password.New));
                        await _service.UpdateStudentAsync(updatedStudent);
                        HttpContext.Session.AddToastNotification(new ToastNotification { Message = "Password has been changed!", Status = ToastColor.Success });
                        return Redirect("/Account");
                    }
                }
                else
                {
                    ModelState.AddModelError("Password.Old", "Wrong password");

                }
            }
            catch (Exception ex)
            {
                await Console.Out.WriteLineAsync(ex.Message);
                ModelState.AddModelError("Password", "Something went wrong");
            }

            return await OnGetAsync();
        }

        #endregion

        #region Update Profile Picture

        [BindProperty]
        [Required]
        [DataType(DataType.Upload)]
        [FileTypesAttributes(new String[] { "png", "jpg", "jpeg", "gif" })]
        public IFormFile Image { get; set; }

        public async Task<IActionResult> OnPostUpdateProfilePictureAsync()
        {
            try
            {
                if (ModelState.GetFieldValidationState("Image") == ModelValidationState.Invalid)
                {
                    return await OnGetAsync();
                }

                Guid guid = Guid.NewGuid();
                string fileName = guid.ToString() + "." + Image.ContentType.Split('/').Last();
                string filePath = Path.Combine(_environment.ContentRootPath, "wwwroot\\img\\", fileName);
                using (FileStream fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await Image.CopyToAsync(fileStream);
                }

                Student student = await _service.GetStudentAsync(Convert.ToInt32(HttpContext.Session.GetInt32("Id")));

                if (student.Image != null || student.Image == "default.png")
                {
                    string oldFilePath = Path.Combine(_environment.ContentRootPath, "wwwroot\\img\\", student.Image);
                    if (System.IO.File.Exists(oldFilePath))
                    {
                        System.IO.File.Delete(oldFilePath);
                    }
                }

                await _service.UpdateStudentAsync(new Student(student.Id, student.Name, fileName, student.Description, student.Email, student.Speciality, student.ClassId, student.EndDate, student.Password));
                HttpContext.Session.AddToastNotification(new ToastNotification { Message = "Profile picture has been updated!", Status = ToastColor.Success });
                return Redirect("/Account");
            }
            catch (Exception ex)
            {
                await Console.Out.WriteLineAsync(ex.Message);
                ModelState.AddModelError("Image", "Something went wrong.");
            }

            return await OnGetAsync();
        }

        #endregion

    }
}

BlaaBog/SBO.BlaaBog.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SBO.BlaaBog.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

BlaaBog/SBO.BlaaBog.Web/Pages/Students.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Caching.Memory;
using SBO.BlaaBog.Domain.Entities;
using SBO.BlaaBog.Services.Services;
using SBO.BlaaBog.Web.DTO;
using SBO.BlaaBog.Web.Utils;
using System.ComponentModel.DataAnnotations;
using System.Reflection;

namespace SBO.BlaaBog.Web.Pages
{
    public class StudentsModel : PageModel
    {
        private readonly StudentService _studentService;
        private readonly CommentService _commentService;
        private readonly ClassService _classService;
        private readonly ReportService _reportService;

        public StudentsModel(IMemoryCache cache)
        {
            _studentService = new StudentService();
            _commentService = new CommentService();
            _classService = new ClassService();
            _reportService = new ReportService();
        }

        public Student Student { get; set; }
        public Class Class { get; set; }
        public List<Comment> Comments { get; set; } = new List<Comment>();

        #region Pagination
        public int PageItems { get; set; } = 5;
        public int CurrentPage { get; set; } = 1;
        public double TotalPage
        {
            get
            {
                return Math.Ceiling((double)Comments.Count / PageItems);
            }
        }

        public int StartPage
        {
            get
            {
                int startPage = CurrentPage < 3 ? 1 : CurrentPage - 2; // Sets the start page to 1 if the current page is less than 3, otherwise it sets it to the current page - 2
                startPage = (TotalPage - startPage) < 4 ? (int)TotalPage - 4 : startPage; // Sets the start page to the total page - 4 if the total page - start page is less than 4, otherwise it sets it to the start page
                startPage = startPage < 1 ? 1 : startPage; // Sets the start page to 1 if the start page is less than 1
                return startPage;
            }
            set { }
        }

        public int EndPage
        {
            get
            {
                int endPage = StartPage + 4;
                endPage = (TotalPage < endPage) ? (int)TotalPage : endPage;
                return endPage;
            }
            set { }
        }

        public List<Comment> DisplayedComments
        {
            get
            {
                int startIndex = (CurrentPage - 1) * PageItems;
                return Comments.Skip(startIndex).Take(PageItems).ToList();
            }
        }

        #endregion

        public List<SelectListItem> Reasons { get; set; } = new()
        {
            new SelectListItem { Text = "Inappropriate" },
            new SelectListItem { Text = "Hurtful" },
            new SelectListItem { Text = "Spam" },
            new SelectListItem { Text = "Other", Value = "" }
        };

        public async Task<IActionResult> OnGetAsync(int id)
        {
            string? PageNumber = Request.Query["page"];
            if (PageNumber != null && Int32.TryParse(PageNumber, out int result))
            {
                CurrentPage = Math.Max(Int32.Parse(PageNumber), 1);
            }

            try
            {
                Student = await _studentService.GetStudentAsync(id);
                if (Student == null)
                {
                    return Redirect("/");
                }

                Class = await _classService.GetClassAsync(Student.ClassId);
                List<Comment> comments = await _commentService.GetCommentsBySubjectAsync(id);

                foreach (Comment com in comments)
                {
                    com.Author = await _studentService.GetStudentAsync(com.AuthorId);
                    Comments.Add(com);
                }

                Comments = Comments.OrderByDescending(c => c.CreatedAt).ToList();

            }
            catch (Exception ex)
            {
                await Console.Out.WriteLineAsync(ex.Message);
            }

            return Page();
        }

        #region Comment

        [BindProperty]
        public CommentDTO Comment { get; set; }
        public async Task<IActionResult> OnPostAsync(int id)
        {
            if (ModelState.GetFieldValidationState("Comment.Content") == ModelValidationState.Valid)
            {
                try
                {
                    if (HttpContext.Items["User"] is Student)
                    {
                        Comment comment = new Comment
                        {
                            AuthorId = Convert.ToInt32(HttpContext.Session.GetInt32("Id")),
                            SubjectId = id,
                            Content = Comment.Content
                        };
                        await _commentService.CreateCommentAsync(comment);
                        HttpContext.Session.AddToastNotification(new ToastNotification { Message = "Comment has been sent!", Status = ToastColor.Success });
                    }
                    else
                    {
                        HttpContext.Session.AddToastNotification(new ToastNotification { Message = "Only students can send comments!", Status = ToastColor.Danger });
                    }
                }
                catch (Exception ex)
                {
                    await Console.Out.WriteLineAsync(ex.Message);
                    HttpContext.Session.AddToastNotification(new ToastNotification { Message = "Something went wrong!", Status = ToastColor.Danger });
                }
            }

            return Redirect(HttpContext.Request.Path + "#comments");
        }

        #endregion

        #region Delete Comment

        public async Task<IActionResult> OnPostDeleteCommentAsync(int delId)
        {
            try
            {
                Comment comment = await _commentService.GetCommentAsync(delId);
                if (comment != null)
                {
                    List<Report> reports = await _reportService.GetReportsByCommentAsync(delId);
                    if (reports != null)
                    {
                        foreach (Report report in reports)
                        {
                            _reportService.DeleteReportAsync(Convert.ToInt32(report.Id));
                        }
                    }
                    await _commentService.DeleteCommentAsync(delId);
                    HttpContext.Session.AddToastNotification(new ToastNotification { Message = "Comment has been deleted!", Status = ToastColor.Success });
                }
            }
            catch (Exception ex)
            {
                await Console.Out.WriteLineAsync(ex.Message);
                HttpContext.Session.AddToastNotification(new ToastNotification { Message = "Something went wrong!", Status = ToastColor.Danger });
            }

            return Redirect(HttpContext.Request.Path + "#comments");
        }

        #endregion

        #region Report Comment

        [BindProperty]
        public ReportDTO Report { get; set; }

        public async Task<IActionResult> OnPostReportCommentAsync(int id, int comment)
        {

            Report.Reason = Report.Reason == null ? Report.CustomReason : Report.Reason;
            Report.CommentId = comment;
            if (Report.Reason == null)
            {
                ModelState.AddModelError("Report.Reason", "Reason is required");
                HttpContext.Items["reportModalId"] = comment;
                return await OnGetAsync(id);
            }
            else if (Report.CustomReason == null && Report.Reason == null)
            {
                ModelState.AddModelError("Report.CustomReason", "You need to type a reason");
                HttpContext.Items["reportModalId"] = comment;
                return await OnGetAsync(id);
            }

            try
            {
                if (await _commentService.GetCommentAsync(comment) != null)
                {
                    await _reportService.CreateReportAsync(new Report { CommentId = Report.CommentId, Reason = Report.Reason });
                    HttpContext.Session.AddToastNotification(new ToastNotification { Message = "Comment has been reported!", Status = ToastColor.Success });
                }
            }
            catch (Exception ex)
            {
                await Console.Out.WriteLineAsync(ex.Message);
                HttpContext.Session.AddToastNotification(new ToastNotification { Message = "Something went wrong!", Status = ToastColor.Danger });
            }

            return Redirect(HttpContext.Request.Path + "#comments");
        }

        #endregion


    }
}

BlaaBog/SBO.BlaaBog.Web/Pages/Account.cshtml
@page
@using Microsoft.AspNetCore.Mvc.ModelBinding;
@using SBO.BlaaBog.Domain.Entities;
@model SBO.BlaaBog.Web.Pages.AccountModel
@{
    ViewData["Title"] = "Account";
}


<div class="row">
    <div class="col-md-4">

        <div class="card mb-3">
            <form method="post" asp-page-handler="UpdateProfilePicture" enctype="multipart/form-data">
                <div class="card-header">
                    <div class="row">
                        <div class="col">
                            <h4 class="mb-0">Profile Picture</h4>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        <img style="aspect-ratio:1/1;" class="img-fluid rounded w-100 h-100" src="~/img/@Model.ImageName" />
                    </div>
                    <hr />
                    <div class="input-group has-validation">
                        <input asp-for="Image" aria-describedby="image" accept=".png,.jpg,.jpeg,.gif" type="file" class="form-control @(ModelState.GetFieldValidationState("Image") == ModelValidationState.Invalid ? "is-invalid" : ModelState.GetValidationState("Image") == ModelValidationState.Valid ? "is-valid" : "")" required />
                        <button class="btn btn-outline-secondary" type="submit" id="image">Upload</button>
                        <span asp-validation-for="Image" class="invalid-feedback w-100 text-center"></span>
                    </div>
                </div>
            </form>
        </div>

    </div>
    <div class="col-md-8">

        <div class="card mb-3">
            <form method="post" asp-page-handler="ChangeAccountDetails">
                <div class="card-header">
                    <div class="row">
                        <div class="col">
                            <h4 class="mb-0">Account Details</h4>
                        </div>
                        <div class="col-auto me-auto">
                            <button type="reset" class="btn btn-sm btn-outline-danger"><i class="fa-solid fa-xmark fa-fw"></i></button>
                            <button type="submit" class="btn btn-outline-primary btn-sm"><i class="fa-solid fa-check fa-fw"></i></button>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md mb-3">
                            <label asp-for="Student.Name" class="form-label">Name</label>
                            <input asp-for="Student.Name" value="@Model.Student.Name" type="text" class="form-control @(ModelState.GetFieldValidationState("Student.Name") == ModelValidationState.Invalid ? "is-invalid" : ModelState.GetValidationState("Student.Name") == ModelValidationState.Valid ? "is-valid" : "")" placeholder="Name" />
                            <span asp-validation-for="Student.Name" class="invalid-feedback w-100 text-center"></span>
                        </div>
                        <div class="col-md mb-3">
                            <label asp-for="Student.Email" class="form-label">Email</label>
                            <input asp-for="Student.Email" value="@Model.Student.Email" type="email" class="form-control @(ModelState.GetFieldValidationState("Student.Email") == ModelValidationState.Invalid ? "is-invalid" : ModelState.GetValidationState("Student.Email") == ModelValidationState.Valid ? "is-valid" : "")" placeholder="Email" />
                            <span asp-validation-for="Student.Email" class="invalid-feedback w-100 text-center"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md mb-3">
                            <label asp-for="Student.Speciality" class="form-label">Speciality</label>
                            <select asp-for="Student.Speciality" asp-items="Model.SpecialitiesList" class="form-select @(ModelState.GetFieldValidationState("Student.Speciality") == ModelValidationState.Invalid ? "is-invalid" : ModelState.GetValidationState("Student.Speciality") == ModelValidationState.Valid ? "is-valid" : "")"></select>
                            <span asp-validation-for="Student.Speciality" class="invalid-feedback w-100 text-center"></span>
                        </div>
                        <div class="col-md mb-3">
                            <label class="form-label">End Date</label>
                            <input asp-for="Student.EndDate" value="@(Model.Student.EndDate != null ? Model.Student.EndDate.Value.ToString("yyyy-MM-dd") : null)" type="date" class="form-control @(ModelState.GetFieldValidationState("Student.EndDate") == ModelValidationState.Invalid ? "is-invalid" : ModelState.GetValidationState("Student.EndDate") == ModelValidationState.Valid ? "is-valid" : "")" />
                            <span asp-validation-for="Student.EndDate" class="invalid-feedback w-100 text-center"></span>
                        </div>
                    </div>
                    <div>
                        <label asp-for="Student.Description" class="form-label">Description</label>
                        <textarea asp-for="Student.Description" type="text" rows="3" style="resize:none" class="form-control @(ModelState.GetFieldValidationState("Student.Description") == ModelValidationState.Invalid ? "is-invalid" : ModelState.GetValidationState("Student.Description") == ModelValidationState.Valid ? "is-valid" : "")" placeholder="Description" />@Model.Student.Description</textarea>
                        <span asp-validation-for="Student.Description" class="invalid-feedback w-100 text-center"></span>
                    </div>
                    <span asp-validation-for="Student" class="invalid-feedback w-100 text-center"></span>
                </div>
            </form>
        </div>

        <div class="card mb-3">
            <form method="post" asp-page-handler="ChangePassword">
                <div class="card-header">
                    <div class="row">
                        <div class="col">
                            <h4 class="mb-0">Change Password</h4>
                        </div>
                        <div class="col-auto me-auto">
                            <button type="reset" class="btn btn-sm btn-outline-danger"><i class="fa-solid fa-xmark fa-fw"></i></button>
                            <button type="submit" class="btn btn-outline-primary btn-sm"><i class="fa-solid fa-check fa-fw"></i></button>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <div class="mb-3">
                        <label asp-for="Password.Old" class="form-label">Old Password</label>
                        <input asp-for="Password.Old" class="form-control @(ModelState.GetFieldValidationState("Password.Old") == ModelValidationState.Invalid ? "is-invalid" : ModelState.GetValidationState("Password.Old") == ModelValidationState.Valid ? "is-valid" : "")" placeholder="Old Password" autocomplete="off" />
                        <span asp-validation-for="Password.Old" class="invalid-feedback w-100 text-center"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Password.New" class="form-label">New Password</label>
                        <input asp-for="Password.New" class="form-control @(ModelState.GetFieldValidationState("Password.New") == ModelValidationState.Invalid ? "is-invalid" : ModelState.GetValidationState("Password.New") == ModelValidationState.Valid ? "is-valid" : "")" placeholder="New Password" autocomplete="off" />
                        <span asp-validation-for="Password.New" class="invalid-feedback w-100 text-center"></span>
                    </div>
                    <div>
                        <label asp-for="Password.Confirm" class="form-label">Confirm Password</label>
                        <input asp-for="Password.Confirm" class="form-control @(ModelState.GetFieldValidationState("Password.Confirm") == ModelValidationState.Invalid ? "is-invalid" : ModelState.GetValidationState("Password.Confirm") == ModelValidationState.Valid ? "is-valid" : "")" placeholder="Confirm Password" autocomplete="off" />
                        <span asp-validation-for="Password.Confirm" class="invalid-feedback w-100 text-center"></span>
                        <span asp-validation-for="Password" class="invalid-feedback w-100 text-center"></span>
                    </div>
                </div>
            </form>
        </div>

    </div>
</div>

BlaaBog/SBO.BlaaBog.Web/Pages/Classes.cshtml
@page "{id:int}"
@model SBO.BlaaBog.Web.Pages.ClassesModel
@{
    ViewData["Title"] = Model.Class.Name;
}

<h1 class="text-center">@Model.Class.Name</h1>
<div class="row">
    @if (Model.Students != null)
    {
        @foreach (var student in Model.Students)
        {
            <div class="col-md-3 mb-3">
                <a class="text-decoration-none" href="/Students/@student.Id">
                    <div class="card" style="width: 18rem;">
                        <img style="aspect-ratio:1/1" src="~/img/@student.Image" class="img-fluid rounded card-img-top w-100 h-100" alt="...">
                        <div class="card-body">
                            <h5 class="card-title text-center text-nowrap overflow-hidden" style="text-overflow:ellipsis" data-bs-toggle="tooltip" data-bs-title="@student.Name">@student.Name</h5>
                        </div>
                    </div>
                </a>
            </div>
        }
    }
</div>

@section Scripts{
    <script>
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
    </script>
}

BlaaBog/SBO.BlaaBog.Web/Pages/Index.cshtml
@page
@using SBO.BlaaBog.Domain.Entities;
@model IndexModel
@{
    ViewData["Title"] = "Home";
}


<div class="accordion" id="accordionExample">
    @foreach (Class classItem in Model.Classes)
    {
        @if (classItem.Students.Count > 0)
        {
            <div class="accordion-item">
                <h2 class="accordion-header" id="header-@classItem.Id">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-@classItem.Id" aria-expanded="false" aria-controls="collapse-@classItem.Id">
                        Year @classItem.Name - @classItem.Students.Count student(s)
                    </button>
                </h2>
                <div id="collapse-@classItem.Id" class="accordion-collapse collapse" aria-labelledby="heading-@classItem.Id" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 row-cols-xxl-5">
                            @foreach (Student student in classItem.Students)
                            {
                                <div class="col mb-3">
                                    <a class="text-decoration-none w-100" href="/Students/@student.Id">
                                        <div class="card">
                                            <img src="~/img/@student.Image" style="aspect-ratio: 1/1" class="card-img-top" alt="Profile Picture">
                                            <div class="card-body">
                                                <h5 class="card-title text-center text-truncate" data-bs-toggle="tooltip" title="@student.Name">@student.Name</h5>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        }
    }
</div>




</div>
@section Scripts{
    <script>
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
    </script>
}

BlaaBog/SBO.BlaaBog.Web/Pages/Logout.cshtml
@page
@model SBO.BlaaBog.Web.Pages.LogoutModel
@{
}

BlaaBog/SBO.BlaaBog.Web/Pages/TOS.cshtml
@page
@model PrivacyModel
@{
    ViewData["Title"] = "Terms of Service";
}
<h1>@ViewData["Title"]</h1>

<p>N/A.</p>