BlaaBog/SBO.BlaaBog.Web/Pages/Account.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.OpenApi.Extensions;
using SBO.BlaaBog.Domain.Entities;
using SBO.BlaaBog.Services.Services;
using SBO.BlaaBog.Web.DTO;
using SBO.BlaaBog.Web.Extensions.DataAnnotations;
using SBO.BlaaBog.Web.Utils;
using System.ComponentModel.DataAnnotations;
using BC = BCrypt.Net.BCrypt;

namespace SBO.BlaaBog.Web.Pages
{
    public class AccountModel : PageModel
    {
        private readonly StudentService _service;
        private readonly IWebHostEnvironment _environment;
        public AccountModel(IWebHostEnvironment environment)
        {
            _service = new StudentService();
            _environment = environment;
        }

        [BindProperty]
        public StudentAccountDTO Student { get; set; }
        public List<SelectListItem> SpecialitiesList { get; set; } = new List<SelectListItem>();
        public string ImageName { get; set; }
        public async Task<IActionResult> OnGetAsync()
        {
            try
            {
                if (HttpContext.Items["User"] is Teacher)
                {
                    return RedirectToPage("/Teachers/Register");
                }

                Student? student = await _service.GetStudentAsync(Convert.ToInt32(HttpContext.Session.GetInt32("Id")));

                Student = new StudentAccountDTO
                {
                    Name = student.Name,
                    Description = student.Description,
                    Email = student.Email,
                    Speciality = student.Speciality,
                    EndDate = student.EndDate
                };

                foreach (Specialities speciality in Enum.GetValues<Specialities>())
                {
                    SpecialitiesList.Add(new SelectListItem { Text = EnumExtensions.GetDisplayName(speciality), Value = speciality.ToString(), Selected = speciality == student.Speciality });
                }

                ImageName = student.Image;
            }
            catch (Exception ex)
            {
                await Console.Out.WriteLineAsync(ex.Message);
                HttpContext.Session.AddToastNotification(new ToastNotification { Message = "Something went wrong!", Status = ToastColor.Danger });

            }

            return Page();
        }

        #region Change Account Details

        public async Task<IActionResult> OnPostChangeAccountDetailsAsync()
        {
            try
            {
                ModelState.Remove(nameof(Image));
                ModelState.Remove(nameof(Password));

                bool emailExists = await _service.GetStudentByEmailAsync(Student.Email) != null;
                Student oldStudent = await _service.GetStudentAsync(Convert.ToInt32(HttpContext.Session.GetInt32("Id")));

                if (emailExists && oldStudent.Email != Student.Email)
                {
                    ModelState.AddModelError("Student.Email", "Email already exists.");
                }

                if (ModelState.GetFieldValidationState("Student.Name") == ModelValidationState.Valid
                    && ModelState.GetFieldValidationState("Student.Email") == ModelValidationState.Valid
                    && ModelState.GetFieldValidationState("Student.Speciality") == ModelValidationState.Valid
                    && ModelState.GetFieldValidationState("Student.EndDate") == ModelValidationState.Valid
                    && ModelState.GetFieldValidationState("Student.Description") == ModelValidationState.Valid)
                {
                    Student updatedStudent = new Student(Convert.ToInt32(HttpContext.Session.GetInt32("Id")), Student.Name, oldStudent.Image, Student.Description ?? "", Student.Email, Student.Speciality, oldStudent.ClassId, Student.EndDate, oldStudent.Password);
                    await _service.UpdateStudentAsync(updatedStudent);
                    HttpContext.Session.SetString("Name", Student.Name);
                    HttpContext.Session.AddToastNotification(new ToastNotification { Message = "Account details have been changed!", Status = ToastColor.Success });
                    return Redirect("/Account");
                }
            }
            catch (Exception ex)
            {
                await Console.Out.WriteLineAsync(ex.Message);
                ModelState.AddModelError("Student", "Something went wrong");
            }

            return await OnGetAsync();
        }
        #endregion

        #region Change Password

        [BindProperty]
        public ChangePasswordDTO Password { get; set; }

        public async Task<IActionResult> OnPostChangePasswordAsync()
        {
            try
            {
                ModelState.Remove(nameof(Image));

                Student student = await _service.GetStudentAsync(Convert.ToInt32(HttpContext.Session.GetInt32("Id")));
                bool validatePassword = BC.EnhancedVerify(Password.Old ?? String.Empty, student.Password);

                if (validatePassword)
                {
                    if (ModelState.GetFieldValidationState("Password.Old") == ModelValidationState.Valid
                    && ModelState.GetFieldValidationState("Password.New") == ModelValidationState.Valid
                    && ModelState.GetFieldValidationState("Password.Confirm") == ModelValidationState.Valid)
                    {
                        Student updatedStudent = new Student(Convert.ToInt32(HttpContext.Session.GetInt32("Id")), student.Name, student.Image, student.Description, student.Email, student.Speciality, student.ClassId, student.EndDate, BC.EnhancedHashPassword(Password.New));
                        await _service.UpdateStudentAsync(updatedStudent);
                        HttpContext.Session.AddToastNotification(new ToastNotification { Message = "Password has been changed!", Status = ToastColor.Success });
                        return Redirect("/Account");
                    }
                }
                else
                {
                    ModelState.AddModelError("Password.Old", "Wrong password");

                }
            }
            catch (Exception ex)
            {
                await Console.Out.WriteLineAsync(ex.Message);
                ModelState.AddModelError("Password", "Something went wrong");
            }

            return await OnGetAsync();
        }

        #endregion

        #region Update Profile Picture

        [BindProperty]
        [Required]
        [DataType(DataType.Upload)]
        [FileTypesAttributes(new String[] { "png", "jpg", "jpeg", "gif" })]
        public IFormFile Image { get; set; }

        public async Task<IActionResult> OnPostUpdateProfilePictureAsync()
        {
            try
            {
                if (ModelState.GetFieldValidationState("Image") == ModelValidationState.Invalid)
                {
                    return await OnGetAsync();
                }

                Guid guid = Guid.NewGuid();
                string fileName = guid.ToString() + "." + Image.ContentType.Split('/').Last();
                string filePath = Path.Combine(_environment.ContentRootPath, "wwwroot\\img\\", fileName);
                using (FileStream fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await Image.CopyToAsync(fileStream);
                }

                Student student = await _service.GetStudentAsync(Convert.ToInt32(HttpContext.Session.GetInt32("Id")));

                if (student.Image != null || student.Image == "default.png")
                {
                    string oldFilePath = Path.Combine(_environment.ContentRootPath, "wwwroot\\img\\", student.Image);
                    if (System.IO.File.Exists(oldFilePath))
                    {
                        System.IO.File.Delete(oldFilePath);
                    }
                }

                await _service.UpdateStudentAsync(new Student(student.Id, student.Name, fileName, student.Description, student.Email, student.Speciality, student.ClassId, student.EndDate, student.Password));
                HttpContext.Session.AddToastNotification(new ToastNotification { Message = "Profile picture has been updated!", Status = ToastColor.Success });
                return Redirect("/Account");
            }
            catch (Exception ex)
            {
                await Console.Out.WriteLineAsync(ex.Message);
                ModelState.AddModelError("Image", "Something went wrong.");
            }

            return await OnGetAsync();
        }

        #endregion

    }
}

BlaaBog/SBO.BlaaBog.Web/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Memory;
using SBO.BlaaBog.Domain.Entities;
using SBO.BlaaBog.Services.Services;
using SBO.BlaaBog.Web.DTO;
using BC = BCrypt.Net.BCrypt;

namespace SBO.BlaaBog.Web.Pages
{
    public class LoginModel : PageModel
    {
        private readonly StudentService _studentService;
        private readonly IMemoryCache _cache;
        public LoginModel(IMemoryCache cache)
        {
            _studentService = new StudentService();
            _cache = cache;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            return Page();
        }

        [BindProperty]
        public LoginDTO Login { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return await OnGetAsync();
                }

                Student? student = await _studentService.GetStudentByEmailAsync(Login.Email);

                if (student != null)
                {
                    bool validatePassword = BC.EnhancedVerify(Login.Password, student.Password);
                    if (validatePassword)
                    {
                        HttpContext.Session.SetInt32("Id", Convert.ToInt32(student.Id));
                        HttpContext.Session.SetString("Name", student.Name);
                        _cache.Set(HttpContext.Session.Id, student);
                        return RedirectToPage("/Index");
                    }
                    else
                    {
                        await Console.Out.WriteLineAsync("Wrong password");
                        ModelState.AddModelError("Login", "Wrong email or password");
                    }
                }
                else
                {
                    await Console.Out.WriteLineAsync("Student is null");
                    ModelState.AddModelError("Login", "Wrong email or password");
                }
            }
            catch (Exception exception)
            {
                await Console.Out.WriteLineAsync(exception.Message);
                ModelState.AddModelError("Login", "Something went wrong");
            }

            return await OnGetAsync();
        }
    }
}

BlaaBog/SBO.BlaaBog.Web/Pages/Teacher/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SBO.BlaaBog.Web.Pages.Teacher
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BlaaBog/SBO.BlaaBog.Web/Pages/Teacher/Register.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SBO.BlaaBog.Web.Pages.Teacher
{
    public class RegisterModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BlaaBog/SBO.BlaaBog.Web/Pages/Teachers/Accounts.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Win32;
using SBO.BlaaBog.Domain.Entities;
using SBO.BlaaBog.Services.Services;
using SBO.BlaaBog.Web.DTO;
using SBO.BlaaBog.Web.Utils;
using BC = BCrypt.Net.BCrypt;

namespace SBO.BlaaBog.Web.Pages.Teachers
{
    public class AccountsModel : PageModel
    {
        private readonly TeacherService _teacherService;
        public AccountsModel()
        {
            _teacherService = new TeacherService();
        }

        public List<Teacher> Teachers { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            try
            {
                Teachers = await _teacherService.GetTeachersAsync();
            }
            catch (Exception exception)
            {
                await Console.Out.WriteLineAsync(exception.Message);
            }

            return Page();
        }

        #region Create Account

        [BindProperty]
        public RegisterDTO CreateAccount { get; set; }

        public async Task<IActionResult> OnPostCreate()
        {
            try
            {
                Teacher? teacherFound = await _teacherService.GetTeacherByEmailAsync(CreateAccount.Email);

                if (teacherFound != null)
                {
                    ModelState.AddModelError("CreateAccount.Email", "Email already in use");
                }

                if (
                    ModelState.GetFieldValidationState("CreateAccount.Name") == ModelValidationState.Invalid ||
                    ModelState.GetFieldValidationState("CreateAccount.Email") == ModelValidationState.Invalid ||
                    ModelState.GetFieldValidationState("CreateAccount.Password") == ModelValidationState.Invalid ||
                    ModelState.GetFieldValidationState("CreateAccount.ConfirmPassword") == ModelValidationState.Invalid
                    )
                {
                    return await OnGetAsync();
                }

                string passwordHash = BC.EnhancedHashPassword(CreateAccount.Password);
                Teacher teacher = new Teacher(0, CreateAccount.Name, CreateAccount.Email, passwordHash, false);

                bool success = await _teacherService.CreateTeacherAsync(teacher);

                if (success)
                {
                    HttpContext.Session.AddToastNotification(new ToastNotification { Message = "Account has been created!", Status = ToastColor.Success });
                    return RedirectToPage("/Teachers/Accounts");
                }
                else
                {
                    ModelState.AddModelError("Register", "Something went wrong");
                }
            }
            catch (Exception exception)
            {
                await Console.Out.WriteLineAsync(exception.Message);
                ModelState.AddModelError("Register", "Something went wrong");
            }

            return await OnGetAsync();
        }

        #endregion

        #region Edit Account

        [BindProperty]
        public EditTeacherDTO EditAccount { get; set; }
        
        public int EditAccountId { get; set; }

        public async Task<IActionResult> OnPostEditAsync(int id)
        {
            try
            {
                EditAccountId = id;

                Teacher? teacherFound = await _teacherService.GetTeacherByEmailAsync(CreateAccount.Email);

                if (teacherFound != null)
                {
                    ModelState.AddModelError("EditAccount.Email", "Email already in use");
                }

                if (
                    ModelState.GetFieldValidationState("EditAccount.Name") == ModelValidationState.Invalid ||
                    ModelState.GetFieldValidationState("EditAccount.Email") == ModelValidationState.Invalid ||
                    ModelState.GetFieldValidationState("EditAccount.Admin") == ModelValidationState.Invalid
                    )
                {
                    return await OnGetAsync();
                }

                Teacher teacher = await _teacherService.GetTeacherAsync(id);
                Teacher newTeacher = new Teacher(id, EditAccount.Name, EditAccount.Email, teacher.Password, EditAccount.Admin);

                bool status = await _teacherService.UpdateTeacherAsync(newTeacher);

                if (status)
                {
                    HttpContext.Session.AddToastNotification(new ToastNotification { Message = "Account has been updated!", Status = ToastColor.Success });
                    return RedirectToPage("/Teachers/Accounts");
                }
                else
                {
                    ModelState.AddModelError("Edit", "Something went wrong");

                    return await OnGetAsync();
                }
            }
            catch (Exception exception)
            {
                await Console.Out.WriteLineAsync(exception.Message);
                ModelState.AddModelError("Edit", "Something went wrong");
            }

            return Redirect("/Teachers/Accounts");
        }

        #endregion

        #region Delete Account

        [BindProperty]
        public int DeleteAccount { get; set; }

        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            try
            {
                bool status = await _teacherService.DeleteTeacherAsync(id);
                if (status)
                {
                    HttpContext.Session.AddToastNotification(new ToastNotification { Message = "Account has been deleted!", Status = ToastColor.Success });
                }
            }
            catch (Exception exception)
            {
                await Console.Out.WriteLineAsync(exception.Message);
                HttpContext.Session.AddToastNotification(new ToastNotification { Message = "Something went wrong", Status = ToastColor.Danger });
            }

            return Redirect("/Teachers/Accounts");
        }

        #endregion
    }
}

BlaaBog/SBO.BlaaBog.Web/Pages/Teachers/Accounts.cshtml
@page
@using Microsoft.AspNetCore.Mvc.ModelBinding;
@using SBO.BlaaBog.Domain.Entities;
@model SBO.BlaaBog.Web.Pages.Teachers.AccountsModel
@{
    ViewData["Title"] = "Teachers";
}


<div class="row mb-3">
    <div class="col d-flex justify-content-end">
        <button class="btn btn-primary float-right" data-bs-toggle="modal" data-bs-target="#create-account-modal"><i class="fa-solid fa-plus fa-fw"></i></button>
    </div>
</div>

<div>
    <table id="accounts" class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Email</th>
                <th>Admin</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (Teacher teacher in Model.Teachers)
            {
                <tr>
                    <td>@teacher.Id</td>
                    <td>@teacher.Name</td>
                    <td>@teacher.Email</td>
                    <td>@teacher.Admin</td>
                    <td class="d-flex justify-content-end">

                        <div class="modal fade" id="edit-@teacher.Id-modal" tabindex="-1" aria-labelledby="edit-@teacher.Id-modal" aria-hidden="false">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <form method="post" asp-page-handler="Edit" asp-route-id="@teacher.Id">
                                        <div class="modal-header">
                                            <h1 class="modal-title fs-5">Edit Teacher</h1>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <div class="mb-3">
                                                <div class="mb-3">
                                                    <label asp-for="EditAccount.Name" class="form-label">Name</label>
                                                    <input type="text" value="@teacher.Name" asp-for="EditAccount.Name" class="form-control @(ModelState.GetFieldValidationState("EditAccount.Name") == ModelValidationState.Invalid ? "is-invalid" : ModelState.GetValidationState("EditAccount.Name") == ModelValidationState.Valid ? "is-valid" : "")" placeholder="Name" required>
                                                    <span asp-validation-for="EditAccount.Name" class="invalid-feedback"></span>
                                                </div>
                                                <div class="mb-3">
                                                    <label asp-for="EditAccount.Email" class="form-label">Email</label>
                                                    <input type="email" value="@teacher.Email" asp-for="EditAccount.Email" class="form-control @(ModelState.GetFieldValidationState("EditAccount.Email") == ModelValidationState.Invalid ? "is-invalid" : ModelState.GetValidationState("EditAccount.Email") == ModelValidationState.Valid ? "is-valid" : "")" placeholder="Email" required>
                                                    <span asp-validation-for="EditAccount.Email" class="invalid-feedback"></span>
                                                </div>
                                                <div class="mb-3">
                                                    <label class="form-label">Permissions</label>
                                                    <div class="form-check">
                                                        <input type="checkbox" asp-for="EditAccount.Admin" value="true" checked="@teacher.Admin" class="form-check-input @(ModelState.GetFieldValidationState("EditAccount.Email") == ModelValidationState.Invalid ? "is-invalid" : ModelState.GetValidationState("EditAccount.Email") == ModelValidationState.Valid ? "is-valid" : "")">
                                                        <label asp-for="EditAccount.Admin" class="form-check-label">
                                                            Admin
                                                        </label>
                                                        <span asp-validation-for="EditAccount.Admin" class="invalid-feedback"></span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="reset" class="btn btn-danger" data-bs-dismiss="modal"><i class="fa-solid fa-xmark fa-fw"></i></button>
                                            <button type="submit" class="btn btn-success"><i class="fa-solid fa-check fa-fw"></i></button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>

                        <button class="btn btn-outline-primary me-2" data-bs-toggle="modal" data-bs-target="#edit-@teacher.Id-modal"><i class="fa-solid fa-pen fa-fw"></i></button>
                        <form method="post" asp-page-handler="Delete" asp-route-id="@teacher.Id">
                            <button type="submit" class="btn btn-outline-danger"><i class="fa-solid fa-trash-can fa-fw"></i></button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="modal fade" id="create-account-modal" tabindex="-1" aria-labelledby="create-account-modal-label" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form method="post" asp-page-handler="Create">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="create-account-modal-label">Create Teacher</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label class="form-label">Name</label>
                        <input asp-for="CreateAccount.Name" class="form-control @(ModelState.GetFieldValidationState("CreateAccount.Name") == ModelValidationState.Invalid ? "is-invalid" : ModelState.GetValidationState("CreateAccount.Name") == ModelValidationState.Valid ? "is-valid" : "")" required />
                        <span asp-validation-for="CreateAccount.Name" class="invalid-feedback w-100 text-center"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Email</label>
                        <input asp-for="CreateAccount.Email" class="form-control @(ModelState.GetFieldValidationState("CreateAccount.Email") == ModelValidationState.Invalid ? "is-invalid" : ModelState.GetValidationState("CreateAccount.Email") == ModelValidationState.Valid ? "is-valid" : "")" required />
                        <span asp-validation-for="CreateAccount.Email" class="invalid-feedback w-100 text-center"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Password</label>
                        <input asp-for="CreateAccount.Password" class="form-control @(ModelState.GetFieldValidationState("CreateAccount.Password") == ModelValidationState.Invalid ? "is-invalid" : ModelState.GetValidationState("CreateAccount.Password") == ModelValidationState.Valid ? "is-valid" : "")" required />
                        <span asp-validation-for="CreateAccount.Password" class="invalid-feedback w-100 text-center"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Confirm Password</label>
                        <input asp-for="CreateAccount.ConfirmPassword" class="form-control @(ModelState.GetFieldValidationState("CreateAccount.ConfirmPassword") == ModelValidationState.Invalid ? "is-invalid" : ModelState.GetValidationState("CreateAccount.ConfirmPassword") == ModelValidationState.Valid ? "is-valid" : "")" required />
                        <span asp-validation-for="CreateAccount.ConfirmPassword" class="invalid-feedback w-100 text-center"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="reset" class="btn btn-danger" data-bs-dismiss="modal"><i class="fa-solid fa-xmark fa-fw"></i></button>
                    <button type="submit" class="btn btn-success"><i class="fa-solid fa-check fa-fw"></i></button>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts {
    @if (
        ModelState.GetFieldValidationState("CreateAccount.Name") == ModelValidationState.Invalid ||
        ModelState.GetFieldValidationState("CreateAccount.Email") == ModelValidationState.Invalid ||
        ModelState.GetFieldValidationState("CreateAccount.Password") == ModelValidationState.Invalid ||
        ModelState.GetFieldValidationState("CreateAccount.ConfirmPassword") == ModelValidationState.Invalid
    )
    {
        <script>
            const createAccountModal = new bootstrap.Modal('#create-account-modal')
            createAccountModal.show();
        </script>
    }

    <script>
        new DataTable(
            '#accounts',
            {
                "columnDefs": [
                    {
                        "orderable": false,
                        "targets": -1
                    },
                    {
                        "orderable": true,
                        "targets": 0
                    }
                ],
                "order": [
                    [
                        0,
                        "desc"
                    ]
                ]
            }
        );
    </script>
}

BlaaBog/SBO.BlaaBog.Web/Pages/Teachers/Reports.cshtml
@page
@model SBO.BlaaBog.Web.Pages.Teachers.ReportsModel
@{
    ViewData["Title"] = "Reports";
}


<div>
    <table id="reports" class="table table-striped">
        <thead>
            <tr>
                <td>#</td>
                <th>Reason</th>
                <th>Created At</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var Report in Model.Reports)
            {
                <tr>
                    <td>@Report.Id</td>
                    <td>@Report.Reason</td>
                    <td>@Report.CreatedAt</td>
                    <td>
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#report-@Report.Id">

                            <i class="fa-solid fa-up-right-from-square"></i>
                        </button>
                    </td>

                </tr>

            }

        </tbody>

    </table>
</div>

@foreach (var report in Model.Reports)
{
    <div class="modal fade" id="report-@report.Id" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">

                    <h1 class="modal-title fs-5" id="exampleModalLabel">Reported Comment</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <h5>Comment</h5>
                    <p>@report.Comment.Content</p>
                    <h5>Reason</h5>
                    <p>@report.Reason</p>
                </div>

                <form id="delete-@report.Id" method="post" asp-page-handler="Delete" asp-route-id="@report.Id">
                </form>

                <form id="approve-@report.Id" method="post" asp-page-handler="Approve" asp-route-id="@report.Id">
                </form>
                <div class="modal-footer">
                    <h5>Do you want to delete this comment?</h5>
                    <button form="approve-@report.Id" type="submit" class="btn btn-success"><i class="fa-solid fa-check"></i></button>

                    <h5>Do you want to delete the report?</h5>
                    <button form="delete-@report.Id" type="submit" class="btn btn-danger"><i class="fa-solid fa-trash"></i></button>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts{


    <script>
        new DataTable(
            '#reports',
            {
                "columnDefs": [
                    {
                        "orderable": false,
                        "targets": -1
                    },
                    {
                        "orderable": true,
                        "targets": 0
                    }
                ],
                "order": [
                    [
                        0,
                        "desc"
                    ]
                ]
            }
        );
    </script>
}